app/models.py
from datetime import datetime
from app.extensions import db


class User(db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True)
    password = db.Column(db.String(255))
    is_active = db.Column(db.Boolean, default=True)


class Employee(db.Model):
    __tablename__ = "employees"

    id = db.Column(db.Integer, primary_key=True)
    firstname = db.Column(db.String(64), nullable=False)
    lastname = db.Column(db.String(64), nullable=False)
    gender = db.Column(db.Enum("M", "F"), nullable=False)
    date_of_birth = db.Column(db.String(16), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    phone_number = db.Column(db.String(20), unique=True, nullable=False)
    address = db.Column(db.String(100), nullable=False)
    position = db.Column(db.String(100), nullable=False)
    department = db.Column(db.String(100), nullable=False)
    created_at = db.Column(db.String(16), default=datetime.utcnow)
    salary = db.Column(db.Float, nullable=False)
    is_active = db.Column(db.Boolean, default=True)

    def __repr__(self):
        return f"<Employee {self.firstname}>"

app/__init__.py
from flask import Flask

from app.routes import employee_bp, main_bp
from app.extensions import db, migrate


def create_app():
    app = Flask(__name__)
    app.config.from_object("config.Config")

    init_app(app)
    register_blueprints(app)

    from app.models import Employee, User

    return app


def init_app(app: Flask):
    db.init_app(app)
    migrate.init_app(app, db)


def register_blueprints(app: Flask):
    app.register_blueprint(main_bp)
    app.register_blueprint(employee_bp)

app/routes.py
from datetime import datetime

from flask import Blueprint, redirect, render_template, request, url_for

from app.extensions import db
from app.models import Employee, User

main_bp = Blueprint("main_bp", __name__)
employee_bp = Blueprint("employee_bp", __name__, url_prefix="/employees")


@main_bp.route("/", methods=["POST", "GET"])
def dashboard():
    employees = Employee.query.all()
    return render_template("dashboard.html", employees=employees)


@employee_bp.route("/create/", methods=["POST", "GET"])
def employee_create():
    if request.method == "POST":
        employee = Employee()
        employee.firstname = request.form["firstname"]
        employee.lastname = request.form["lastname"]
        employee.gender = request.form["gender"]
        employee.date_of_birth = request.form["date_of_birth"]
        employee.phone_number = request.form["phone_number"]
        employee.email = request.form["email"]
        employee.address = request.form["address"]
        employee.position = request.form["position"]
        employee.department = request.form["department"]
        employee.salary = request.form["salary"]
        employee.is_active = True if "is_active" in request.form else False
        db.session.add(employee)
        db.session.commit()
        return redirect(url_for("employee_bp.employee_list"))
    return render_template("employee_create.html")


@employee_bp.route("/update/<int:id>", methods=["POST", "GET"])
def employee_update(id: int):
    employee = Employee.query.get(id)
    if not employee:
        return redirect(url_for("employee_bp.employee_list"))

    if request.method == "POST":
        employee.firstname = request.form["firstname"]
        employee.lastname = request.form["lastname"]
        employee.gender = request.form["gender"]
        employee.date_of_birth = request.form["date_of_birth"]
        employee.phone_number = request.form["phone_number"]
        employee.email = request.form["email"]
        employee.address = request.form["address"]
        employee.position = request.form["position"]
        employee.department = request.form["department"]
        employee.salary = request.form["salary"]
        employee.is_active = True if "is_active" in request.form else False
        db.session.add(employee)
        db.session.commit()
        return redirect(url_for("employee_bp.employee_list"))
    return render_template("employee_create.html", employee=employee)


@employee_bp.route("/", methods=["POST", "GET"])
def employee_list():
    employees = Employee.query.order_by(Employee.created_at.desc()).all()
    query = request.args.get("search")
    order_by = request.args.get("order_by")

    if query:
        employees = Employee.query.filter(
            (Employee.firstname.contains(query))
            | (Employee.lastname.contains(query))
            | (Employee.position.contains(query))
            | (Employee.department.contains(query))
            | (Employee.salary.contains(query))
        ).all()

    if order_by == "firstname_asc":
        employees = Employee.query.order_by(Employee.firstname).all()
    elif order_by == "firstname_desc":
        employees = Employee.query.order_by(Employee.firstname.desc()).all()
    elif order_by == "lastname_asc":
        employees = Employee.query.order_by(Employee.lastname).all()
    elif order_by == "lastname_desc":
        employees = Employee.query.order_by(Employee.lastname.desc()).all()
    elif order_by == "position_asc":
        employees = Employee.query.order_by(Employee.position).all()
    elif order_by == "position_desc":
        employees = Employee.query.order_by(Employee.position.desc()).all()
    elif order_by == "department_asc":
        employees = Employee.query.order_by(Employee.department).all()
    elif order_by == "department_desc":
        employees = Employee.query.order_by(Employee.department.desc()).all()
    elif order_by == "salary_asc":
        employees = Employee.query.order_by(Employee.salary).all()
    elif order_by == "salary_desc":
        employees = Employee.query.order_by(Employee.salary.desc()).all()
    elif order_by == "status_asc":
        employees = Employee.query.order_by(Employee.is_active).all()
    elif order_by == "status_desc":
        employees = Employee.query.order_by(Employee.is_active.desc()).all()
    elif order_by == "address_asc":
        employees = Employee.query.order_by(Employee.address).all()
    elif order_by == "address_desc":
        employees = Employee.query.order_by(Employee.address.desc()).all()

    employee_list = []
    for employee in employees:
        employee.created_at = datetime.strptime(
            employee.created_at, "%Y-%m-%d %H:%M:%S.%f"
        ).strftime("%Y-%m-%d")
        employee_list.append(employee)
    return render_template("employee_list.html", employees=employee_list)


@employee_bp.route("/delete/<int:id>", methods=["POST", "GET"])
def employee_delete(id: int):
    if employee := Employee.query.get(id):
        db.session.delete(employee)
        db.session.commit()
    return redirect(url_for("employee_bp.employee_list"))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1"
		/>
		<title>Gestion Des Employes</title>
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
			crossorigin="anonymous"
		/>
		<link
			rel="stylesheet"
			href="https://cdn.jsdelivr.net/npm/charts.css/dist/charts.min.css"
		/>
		<script
			src="https://kit.fontawesome.com/d6dbfba604.js"
			crossorigin="anonymous"
		></script>
	</head>

	<body>
		{% block content %}{% endblock %}
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
			crossorigin="anonymous"
		></script>
	</body>
</html>

app/templates/dashboard.html
{% extends 'base.html' %} {% block content %} {% include "navbar.html" %}
<div class="container">
	<div class="row row-cols-1 row-cols-md-2 g-5 py-3">
		<div class="col">
			<table
				class="charts-css column show-heading show-labels show-primary-axis show-10-secondary-axes"
			>
				<caption>
					<strong> Employés par departement </strong>
				</caption>
				<thead>
					<tr>
						<th scope="col">Departement</th>
						<th scope="col">Nombre employes</th>
					</tr>
				</thead>

				<tbody>
					{% for group in employees|groupby("department") %}
					<tr>
						<th scope="row">{{ group.grouper }}</th>
						<td
							style="--size: {{ group.list|count/employees|count }}"
						>
							<span class="data"> {{ group.list|count }} </span>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		<div class="col">
			<table
				class="charts-css column show-heading show-labels show-primary-axis show-10-secondary-axes"
			>
				<caption>
					<strong> Employés par position </strong>
				</caption>
				<thead>
					<tr>
						<th scope="col">Position</th>
						<th scope="col">Nombre employes</th>
					</tr>
				</thead>

				<tbody>
					{% for group in employees|groupby("position") %}
					<tr>
						<th scope="row">{{ group.grouper }}</th>
						<td
							style="--size: {{ group.list|count/employees|count }}"
						>
							<span class="data"> {{ group.list|count }} </span>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		<div class="col">
			<table
				class="charts-css column show-heading show-labels show-primary-axis show-10-secondary-axes"
			>
				<caption>
					<strong> Employés par salaire </strong>
				</caption>
				<thead>
					<tr>
						<th scope="col">Salaire</th>
						<th scope="col">Nombre employes</th>
					</tr>
				</thead>

				<tbody>
					{% for group in employees|groupby("salary") %}
					<tr>
						<th scope="row">{{ group.grouper / 1000  }}</th>
						<td
							style="--size: {{ group.list|count/employees|count }}"
						>
							<span class="data"> {{ group.list|count }} </span>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		<div class="col">
			<div
				class="d-flex"
				id="pie-example-1"
			>
				<table class="charts-css pie hide-data show-labels">
					<caption>
						Pie Example #1
					</caption>
					<tbody>
						<tr>
							<td
								style="--start: 0; --end: {{ employees|selectattr('is_active')|list|count }} / {{ employees|count }}"
							>
								<span class="data"> $ 10K </span>
							</td>
						</tr>
						<tr>
							<td
								style="--start: {{ employees|selectattr('is_active')|list|count }} / {{ employees|count }}; --end: 1"
							>
								<span class="data"> $ 5K </span>
							</td>
						</tr>
					</tbody>
				</table>
				<ul class="charts-css legend legend-square" style="flex-shrink: 3;">
					<li>Active</li>
					<li>Inactive</li>
				</ul>
			</div>
		</div>
	</div>
</div>
{% endblock %}

app/templates/employee_create.html
{% extends 'base.html' %} {% block content %} {% include "navbar.html" %}
<div class="container">
	<div class="row py-3">
		<div class="col col-md-10 col-lg-8 mx-auto">
			{% include "employee_form.html" %}
		</div>
	</div>
</div>
{% endblock %}

app/templates/employee_delete.html
<div
	class="modal fade"
	id="{{ employee.id }}"
	tabindex="-1"
	aria-labelledby="employee_delete_modal_label"
	aria-hidden="true"
>
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h1
					class="modal-title fs-5"
					id="employee_delete_modal_label"
				>
					Supprimer "{{ employee.lastname }}"
				</h1>
				<button
					type="button"
					class="btn-close"
					data-bs-dismiss="modal"
					aria-label="Close"
				></button>
			</div>
			<div class="modal-footer">
				<a
					class="btn btn-danger"
					href="{{ url_for('employee_bp.employee_delete', id=employee.id) }}"
					role="button"
					>Supprimer</a
				>
				<button
					type="button"
					class="btn btn-secondary"
					data-bs-dismiss="modal"
				>
					Fermer
				</button>
			</div>
		</div>
	</div>
</div>

app/templates/employee_form.html
<form method="post">
	<div class="row row-cols-1 row-cols-md-2 g-3">
		<div class="col">
			<div class="form-floating">
				<input
					type="text"
					class="form-control shadow-none"
					id="firstname"
					placeholder="Nom"
					name="firstname"
					maxlength="32"
					value="{% if employee %}{{ employee.firstname }}{% endif %}"
				/>
				<label for="firstname">Nom</label>
			</div>
		</div>
		<div class="col">
			<div class="form-floating">
				<input
					type="text"
					class="form-control shadow-none"
					id="lastname"
					placeholder="Prénom"
					name="lastname"
					maxlength="32"
					value="{% if employee %}{{ employee.lastname }}{% endif %}"
				/>
				<label for="lastname">Prénom</label>
			</div>
		</div>
		<div class="col">
			<div class="form-floating">
				<select
					class="form-select"
					id="gender"
					name="gender"
					aria-label="Floating label select example"
				>
					{% if employee %}
					{% if employee.gender == "M" %}
					<option value="M" selected>Masculin</option>
					<option value="F">Feminin</option>
					{% else %}
					<option value="M">Masculin</option>
					<option value="F" selected>Feminin</option>
					{% endif %}
					{% else %}
					<option value="M">Masculin</option>
					<option value="F">Feminin</option>
					{% endif %}
				</select>
				<label for="gender">Genre</label>
			</div>
		</div>
		<div class="col">
			<div class="form-floating">
				<input
					type="date"
					class="form-control shadow-none"
					id="date_of_birth"
					placeholder="Date de naissance"
					name="date_of_birth"
					maxlength="32"
					value="{% if employee %}{{ employee.date_of_birth }}{% endif %}"
				/>
				<label for="date_of_birth">Date de naissance</label>
			</div>
		</div>
		<div class="col">
			<div class="form-floating">
				<input
					type="text"
					class="form-control shadow-none"
					id="phone_number"
					placeholder="Téléphone"
					name="phone_number"
					maxlength="100"
					value="{% if employee %}{{ employee.phone_number }}{% endif %}"
				/>
				<label for="phone_number">Téléphone</label>
			</div>
		</div>
		<div class="col">
			<div class="form-floating">
				<input
					type="email"
					class="form-control shadow-none"
					id="email"
					placeholder="Email"
					name="email"
					maxlength="100"
					value="{% if employee %}{{ employee.email }}{% endif %}"
				/>
				<label for="email">Email</label>
			</div>
		</div>
		<div class="col">
			<div class="form-floating">
				<input
					type="text"
					class="form-control shadow-none"
					id="address"
					placeholder="Adresse"
					name="address"
					maxlength="100"
					value="{% if employee %}{{ employee.address }}{% endif %}"
				/>
				<label for="address">Adresse</label>
			</div>
		</div>
		<div class="col">
			<div class="form-floating">
				<input
					type="text"
					class="form-control shadow-none"
					id="position"
					placeholder="Position"
					name="position"
					maxlength="100"
					value="{% if employee %}{{ employee.position }}{% endif %}"
				/>
				<label for="position">Position</label>
			</div>
		</div>
		<div class="col">
			<div class="form-floating">
				<input
					type="text"
					class="form-control shadow-none"
					id="department"
					placeholder="Departement"
					name="department"
					maxlength="100"
					value="{% if employee %}{{ employee.department }}{% endif %}"
				/>
				<label for="department">Departement</label>
			</div>
		</div>
		<div class="col">
			<div class="form-floating">
				<input
					type="number"
					class="form-control shadow-none"
					id="salary"
					placeholder="Salaire"
					name="salary"
					value="{% if employee %}{{ employee.salary }}{% endif %}"
				/>
				<label for="salary">Salaire</label>
			</div>
		</div>
		<div class="col">
			<div class="row row-cols-2 g-3">
				<div class="col">
					<input
						type="checkbox"
						class="btn-check"
						id="is_active"
						name="is_active"
						autocomplete="off"
						{% if employee and employee.is_active %}checked{% endif %}
					/>
					<label
						class="btn btn-outline-primary btn-lg w-100"
						for="is_active"
						>Active</label
					><br />
				</div>
				<div class="col">
					<button
						class="btn btn-primary btn-lg w-100 shadow-none"
						type="submit"
					>
						Enregistrer
					</button>
				</div>
			</div>
			
		</div>
	</div>
</form>

app/templates/employee_list.html
{% extends 'base.html' %} {% block content %} {% include "navbar.html" %}
<div class="container">
	<div class="row row-cols-1 py-3 g-3">
		<div class="col col-md-6 col-lg-4">
			<div class="hstack gap-3">
				<a
					class="btn btn-outline-secondary btn-lg"
					href="{{ url_for('employee_bp.employee_create') }}"
					><i class="fa-solid fa-plus fa-xl"></i
				></a>
				<form method="get">
					<div class="input-group input-group-lg">
						<input
							type="text"
							class="form-control border-secondary border-end-0 shadow-none"
							id="search"
							placeholder="Recherche"
							name="search"
							aria-label="Recipient's username"
							aria-describedby="search-button"
						/>
						<button
							class="btn btn-outline-secondary border-start-0 border-start-0 shadow-none"
							type="submit"
							id="search-button"
						>
							<i class="fa-solid fa-magnifying-glass"></i>
						</button>
					</div>
				</form>
			</div>
		</div>
		<div class="col">
			<div class="row row-cols-1 g-3">
				<div class="table-responsive">
					<table class="table table-hover">
						<thead>
							<tr>
								<th scope="col">#</th>
								<th scope="col">
									Nom {% if 'firstname_asc' in request.url %}
									<a class="stretched-link"
										href="{{ url_for('employee_bp.employee_list', order_by='firstname_desc') }}"
										><i class="fa-solid fa-caret-down"></i
									></a>
									{% else %}
									<a
										href="{{ url_for('employee_bp.employee_list', order_by='firstname_asc') }}"
										><i class="fa-solid fa-caret-up"></i
									></a>
									{% endif %}
								</th>
								<th scope="col">
									Prénom {% if 'lastname_asc' in request.url
									%}
									<a
										href="{{ url_for('employee_bp.employee_list', order_by='lastname_desc') }}"
										><i class="fa-solid fa-caret-down"></i
									></a>
									{% else %}
									<a
										href="{{ url_for('employee_bp.employee_list', order_by='lastname_asc') }}"
										><i class="fa-solid fa-caret-up"></i
									></a>
									{% endif %}
								</th>
								<th scope="col">Genre</th>
								<th scope="col">Date de naissance</th>
								<th scope="col">Date d'embauche</th>
								<th scope="col">Téléphone</th>
								<th scope="col">Email</th>
								<th scope="col">
									Adresse {% if 'address_asc' in request.url %}
									<a
										href="{{ url_for('employee_bp.employee_list', order_by='address_desc') }}"
										><i class="fa-solid fa-caret-down"></i
									></a>
									{% else %}
									<a
										href="{{ url_for('employee_bp.employee_list', order_by='address_asc') }}"
										><i class="fa-solid fa-caret-up"></i
									></a>
									{% endif %}
								</th>
								<th scope="col">
									Position {% if 'position_asc' in request.url %}
									<a
										href="{{ url_for('employee_bp.employee_list', order_by='position_desc') }}"
										><i class="fa-solid fa-caret-down"></i
									></a>
									{% else %}
									<a
										href="{{ url_for('employee_bp.employee_list', order_by='position_asc') }}"
										><i class="fa-solid fa-caret-up"></i
									></a>
									{% endif %}
								</th>
								<th scope="col">
									Departement {% if 'department_asc' in request.url %}
									<a
										href="{{ url_for('employee_bp.employee_list', order_by='department_desc') }}"
										><i class="fa-solid fa-caret-down"></i
									></a>
									{% else %}
									<a
										href="{{ url_for('employee_bp.employee_list', order_by='department_asc') }}"
										><i class="fa-solid fa-caret-up"></i
									></a>
									{% endif %}
								</th>
								<th scope="col">
									Salaire {% if 'salary_asc' in request.url %}
									<a
										href="{{ url_for('employee_bp.employee_list', order_by='salary_desc') }}"
										><i class="fa-solid fa-caret-down"></i
									></a>
									{% else %}
									<a
										href="{{ url_for('employee_bp.employee_list', order_by='salary_asc') }}"
										><i class="fa-solid fa-caret-up"></i
									></a>
									{% endif %}
								</th>
								<th scope="col">
									Status {% if 'status_asc' in request.url %}
									<a
										href="{{ url_for('employee_bp.employee_list', order_by='status_desc') }}"
										><i class="fa-solid fa-caret-down"></i
									></a>
									{% else %}
									<a
										href="{{ url_for('employee_bp.employee_list', order_by='status_asc') }}"
										><i class="fa-solid fa-caret-up"></i
									></a>
									{% endif %}
								</th>
								<th scope="col">Actions</th>
							</tr>
						</thead>
						<tbody>
							{% for employee in employees %}
							<tr>
								<th scope="row">{{ loop.index }}</th>
								<td>{{ employee.lastname }}</td>
								<td>{{ employee.firstname }}</td>
								<td>{{ employee.gender }}</td>
								<td>{{ employee.date_of_birth }}</td>
								<td>{{ employee.created_at }}</td>
								<td>{{ employee.phone_number }}</td>
								<td>{{ employee.email }}</td>
								<td>{{ employee.address }}</td>
								<td>{{ employee.position }}</td>
								<td>{{ employee.department }}</td>
								<td>{{ employee.salary }}</td>
								<td>
									{% if employee.is_active %}<i
										class="fa-solid fa-circle-check text-success"
									></i
									>{% else %}<i
										class="fa-solid fa-circle-xmark text-danger"
									></i
									>{% endif %}
								</td>
								<td>
									<div class="hstack gap-3">
										<a
											class=""
											href="{{ url_for('employee_bp.employee_update', id=employee.id) }}"
											><i
												class="fa-solid fa-pen-to-square fa-sm"
												style="color: #007bff"
												role="button"
											></i
										></a>
										<i
											class="fa-solid fa-trash fa-sm"
											style="color: #ff0000"
											role="button"
											data-bs-toggle="modal"
											data-bs-target="#{{ employee.id }}"
										></i>
									</div>
								</td>
							</tr>
							{% include "employee_delete.html" %} {% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

app/templates/navbar.html
<nav
	class="navbar navbar-dark navbar-expand-md bg-body-tertiary"
	data-bs-theme="dark"
>
	<div class="container">
		<a
			class="navbar-brand"
			href="#"
			>Gestion</a
		>
		<button
			class="navbar-toggler shadow-none p-0 border-0"
			type="button"
			data-bs-toggle="collapse"
			data-bs-target="#navbarSupportedContent"
			aria-controls="navbarSupportedContent"
			aria-expanded="false"
			aria-label="Toggle navigation"
		>
			<span class="navbar-toggler-icon"></span>
		</button>
		<div
			class="collapse navbar-collapse"
			id="navbarSupportedContent"
		>
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<li class="nav-item">
					<a
						class="nav-link {% if request.path == url_for('main_bp.dashboard') %}active{% endif %}"
						href="{{ url_for('main_bp.dashboard') }}"
						>Accueil</a
					>
				</li>
				<li class="nav-item">
					<a
						class="nav-link {% if 'employees' in request.path %}active{% endif %}"
						href="{{ url_for('employee_bp.employee_list') }}"
						>Employés</a
					>
				</li>
			</ul>
		</div>
	</div>
</nav>